name: pr-label-checker
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  pr-label-checker:
    uses: "porterin/dpq-workflows/.github/workflows/pr-label-checker.yml@main"
